let nome = prompt("Digite o seu nome: ")
let idade = Number(prompt("Digite a sua idade: "))
let email = prompt("Digite o seu email: ")
let telefone = Number(prompt("Digite seu telefone: "))
console.log("O seu nome é:", nome)
console.log("Você tem: ", idade, "anos")
console.log("Pertence a você oemail", email)
console.log("e seu número de telefone é: ", telefone)
console.log("Obrigado(a) pelas informações, agora podemos continuar...")